apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  project: default
  source:
    repoURL: https://aquasecurity.github.io/helm-charts
    chart: trivy-operator
    targetRevision: 0.33.2
    helm:
      releaseName: trivy-operator
      valuesObject:
        operator:
          metricsFindingsEnabled: true
          metricsConfigAuditInfo: true
          metricsRbacAssessmentInfo: true
          metricsInfraAssessmentInfo: true
        serviceMonitor:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: trivy-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
