---
nixos_anywhere_extra_args: ""
nixos_flake_path: ../../NixOS
nixos_host: failsafe
nixos_disk: /dev/sda
nixos_ssh_public_key_path: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519.pub"
nixos_extra_files_dir: "{{ playbook_dir }}/../.nixos-anywhere-extra-files/{{ nixos_host }}"
hermes_env_file: "{{ playbook_dir }}/../hermes.env"
hermes_remote_env_file: /var/lib/hermes/env
failsafe_kubeconfig_file: "{{ playbook_dir }}/../failsafe/kubeconfig"
failsafe_hcloud_env_file: "{{ playbook_dir }}/../failsafe/hcloud.env"
failsafe_remote_kubeconfig_file: /var/lib/hermes/kube/config
failsafe_remote_hcloud_env_file: /var/lib/hermes/hcloud.env
