# Copyright (C) 2019, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds wazuh namespace to all resources.
namespace: wazuh

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: indexer-conf
    files:
      - indexer_stack/wazuh-indexer/indexer_conf/opensearch.yml
      - indexer_stack/wazuh-indexer/indexer_conf/internal_users.yml
  - name: wazuh-conf
    files:
      - wazuh_managers/wazuh_conf/master.conf
      - wazuh_managers/wazuh_conf/worker.conf
      - wazuh_managers/wazuh_conf/local_rules.xml
  - name: dashboard-conf
    files:
      - indexer_stack/wazuh-dashboard/dashboard_conf/opensearch_dashboards.yml

resources:
  - base/wazuh-ns.yaml


  - wazuh_managers/wazuh-cluster-svc.yaml
  - wazuh_managers/wazuh-master-svc.yaml
  - wazuh_managers/wazuh-workers-svc.yaml
  - wazuh_managers/wazuh-master-sts.yaml
  - wazuh_managers/wazuh-worker-sts.yaml

  - indexer_stack/wazuh-indexer/indexer-svc.yaml
  - indexer_stack/wazuh-indexer/cluster/indexer-api-svc.yaml
  - indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml

  - indexer_stack/wazuh-dashboard/dashboard-svc.yaml
  - indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
  - wazuh-dashboard.certificate.yaml
  - wazuh-dashboard.serverstransport.yaml
  - wazuh-dashboard.ingressroute.yaml
  - wazuh-agent.daemonset.yaml

images:
  - name: wazuh/wazuh-agent
    newTag: 4.14.6
  - name: wazuh/wazuh-dashboard
    newTag: 4.14.6
  - name: wazuh/wazuh-indexer
    newTag: 4.14.6
  - name: wazuh/wazuh-manager
    newTag: 4.14.6
