apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: qbittorrent
  namespace: media
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.qbitt.local.flyvmed.dk`) # change to your domain
      kind: Rule
      services:
        - name: qbittorrent
          port: 80
    - match: Host(`qbitt.local.flyvmed.dk`) # change to your domain
      kind: Rule
      services:
        - name: qbittorrent
          port: 80
      middlewares:
        - name: default-headers-media
  tls:
    certResolver: letsencrypt
    
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: default-headers-media
  namespace: media
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 15552000
    customFrameOptionsValue: SAMEORIGIN
    customRequestHeaders:
      X-Forwarded-Proto: https