apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qbittorrent-ingress
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`qbitt.local.flyvmed.dk`) && PathPrefix(`/`)
    kind: Rule
    services:
    - kind: Service
      name: qbittorrent
      namespace: media
      port: 8080
  tls:
    certResolver: letsencrypt