apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-applications
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: dionysus
            path: Services/Utilities/Dionysus
            namespace: dionysus
            syncWave: "5"
          - name: wazuh
            path: Services/Security/Wazuh
            namespace: wazuh
            syncWave: "9"
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: '{{syncWave}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/TobiasSaaby/ThePaleHeart.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
