apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ArgoCD/argocd.application.yaml
  - CertManager/cert-manager.application.yaml
  - CertManager/cert-manager-issuers.application.yaml
  - SimplyDNSWebhook/simply-dns-webhook.application.yaml
  - Longhorn/longhorn.application.yaml
  - Woodpecker/woodpecker.application.yaml
  - Dionysus/dionysus.application.yaml
  - Observability/kube-prometheus-stack.application.yaml
  - Observability/loki.application.yaml
  - Observability/promtail.application.yaml
  - Observability/grafana-dashboards.application.yaml
  - TrivyOperator/trivy-operator.application.yaml
  - Falco/falco.application.yaml
  - Wazuh/wazuh.application.yaml
