apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - Clusters:
        - EDZ:
            href: http://10.0.0.11:8006/
            description: European Dead Zone
        - Tower:
            href: http://10.0.0.10:8006/
            description: Tower

    - Utilities:
        - ArgoCD:
            href: https://argocd.local.flyvmed.dk/
            description: Continously deploying infrastructure as code
        - Homeassistant:
            href: https://homeassist.local.flyvmed.dk/
            description: Homeassistant
        - Mealie:
            href: https://mealie.local.flyvmed.dk/
            description: Home of all our recipes

    - Media:
        - Jellyfin:
            href: https://jellyfin.localhost.flyvmed.dk/
            description: Home media server
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""