apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default
  source:
    chart: authentik
    repoURL: https://charts.goauthentik.io
    targetRevision: 2025.2.2
    helm:
      valueFiles:
      - authentik.values.yml
  destination:
    name: authentikk
    namespace: authentik