- hosts: k3s_servers
  become: true
  gather_facts: true

  vars:
    k3s_iface: enp7s0
    k3s_config_dir: /etc/rancher/k3s
    api_domain: "{{ lookup('env', 'K3S_API_DOMAIN') | default('k3s.local', true) }}"

  roles:
    - k3s_server
