apiVersion: v1
kind: Service
metadata:
  name: mealie
  namespace: mealie
  labels:
    app.kubernetes.io/name: mealie
spec:
  ports:
    - name: http
      port: 9925
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: mealie
